// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// greplParallel
Rcpp::DataFrame greplParallel(Rcpp::CharacterVector idVec, Rcpp::List stringList, Rcpp::List keyWordList);
RcppExport SEXP _multiFastGrepl_greplParallel(SEXP idVecSEXP, SEXP stringListSEXP, SEXP keyWordListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type idVec(idVecSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type stringList(stringListSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type keyWordList(keyWordListSEXP);
    rcpp_result_gen = Rcpp::wrap(greplParallel(idVec, stringList, keyWordList));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_multiFastGrepl_greplParallel", (DL_FUNC) &_multiFastGrepl_greplParallel, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_multiFastGrepl(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
