# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getRegexMatches <- function(stringMat, id, patternList) {
    .Call(`_multiFastGrepl_getRegexMatches`, stringMat, id, patternList)
}

greplParallel <- function(idVec, stringList, keyWordList) {
    .Call(`_multiFastGrepl_greplParallel`, idVec, stringList, keyWordList)
}
